image: python:latest

stages:
  - build
  - test
#  - deploy

cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


build-job:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/

unit-test-job:
  stage: test
  script:
    - pip install pytest
    - pip install dist/*.whl
    - pytest

#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
