#
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import abc
from typing import Tuple, Any
import os
import hashlib
import shutil
from typing import Callable
import functools
import onnxruntime as ort
import onnx
import torch

from leapp._logging import _get_logger
from leapp.backends.module_builder import ModuleBuilder


def prepare_tensors_for_export(tensors):
    """
    Prepare tensors for export by cloning them to escape inference mode.
    
    Tensors created under torch.inference_mode() cannot participate in autograd,
    which causes torch.export.export() (used by dynamo) to fail with:
    "RuntimeError: Inference tensors cannot be saved for backward."
    
    Cloning creates new tensors that are not marked as inference tensors.
    
    Args:
        tensors: A sequence of tensors (or other values) to prepare.
        
    Returns:
        A tuple of prepared tensors (cloned if they were torch.Tensor).
    """
    prepared = []
    for t in tensors:
        if isinstance(t, torch.Tensor):
            prepared.append(t.clone())
        else:
            prepared.append(t)
    return tuple(prepared)


class SimplifiedONNXProgram:
    """Wrapper for ONNX models.

    This class mimics the behavior of ONNXProgram generated by torch.onnx.export
    with dynamo=True, allowing the model to be called directly for inference.
    """

    def __init__(self, onnx_model_path, device=None):
        """Initialize the ONNX program.

        Args:
            onnx_model_path: Path to an ONNX file.
            device: Device to run on ('cuda', 'cpu', or None for auto-detect).
                    If None, will use CUDA if available, otherwise CPU.
        """
        self._device = device
        model_path = str(onnx_model_path)
        
        # Create session immediately from file path
        # This is more reliable for large models with external data files
        # The session loads everything into memory, so file can be deleted after
        providers = self._get_providers(device)
        self._session = ort.InferenceSession(model_path, providers=providers)
        self._input_names = [inp.name for inp in self._session.get_inputs()]
        self._active_provider = self._session.get_providers()[0] if self._session.get_providers() else 'CPUExecutionProvider'
        
        # Load model with external data embedded for later save()
        # Store model_proto directly - don't serialize/deserialize (fails for >2GB models)
        self._model_proto = onnx.load(model_path, load_external_data=True)

    @property
    def model_proto(self):
        """Get the ONNX model proto."""
        return self._model_proto

    def _get_providers(self, device):
        """Get the list of execution providers based on device preference."""
        available_providers = ort.get_available_providers()

        if device is None:
            # Auto-detect: prefer CUDA if available
            if 'CUDAExecutionProvider' in available_providers:
                return ['CUDAExecutionProvider', 'CPUExecutionProvider']
            return ['CPUExecutionProvider']
        elif device == 'cuda' or (isinstance(device, torch.device) and device.type == 'cuda'):
            if 'CUDAExecutionProvider' not in available_providers:
                _get_logger().warning(
                    "CUDA execution provider requested but not available. Falling back to CPU."
                )
                return ['CPUExecutionProvider']
            return ['CUDAExecutionProvider', 'CPUExecutionProvider']
        else:
            return ['CPUExecutionProvider']

    def _estimate_model_size(self):
        """Estimate the model size in bytes by summing initializer sizes."""
        if self._model_proto is None:
            return 0
        
        total_size = 0
        for initializer in self._model_proto.graph.initializer:
            # Each element size depends on data type
            # Common types: float32=4, float16=2, int64=8, int32=4
            dtype_sizes = {
                1: 4,   # FLOAT
                2: 1,   # UINT8
                3: 1,   # INT8
                4: 2,   # UINT16
                5: 2,   # INT16
                6: 4,   # INT32
                7: 8,   # INT64
                10: 2,  # FLOAT16
                11: 8,  # DOUBLE
                16: 2,  # BFLOAT16
            }
            elem_size = dtype_sizes.get(initializer.data_type, 4)
            num_elements = 1
            for dim in initializer.dims:
                num_elements *= dim
            total_size += num_elements * elem_size
        
        return total_size

    def save(self, destination, include_initializers=True, keep_initializers_as_inputs=False):
        """Save the ONNX model to disk"""
        # 2GB threshold for protobuf limit
        SIZE_THRESHOLD = 2 * 1024 * 1024 * 1024  # 2GB
        
        estimated_size = self._estimate_model_size()
        
        if estimated_size > SIZE_THRESHOLD:
            # Large model - must use external data
            _get_logger().info(
                f"Model size (~{estimated_size / (1024**3):.2f} GB) exceeds 2GB limit, "
                "saving with external data"
            )
            onnx.save(
                self._model_proto, 
                destination,
                save_as_external_data=True,
                all_tensors_to_one_file=True,
                location=os.path.basename(destination) + ".data",
                size_threshold=1024,
            )
        else:
            # Small model - regular save
            onnx.save(self._model_proto, destination)

    def __call__(self, *args):
        """Run inference on the ONNX model.

        Args:
            *args: Input tensors in order, matching the model's input signature.

        Returns:
            List of output tensors as torch.Tensor objects on the same device as inputs.
        """
        if len(args) != len(self._input_names):
            raise ValueError(
                f"Expected {len(self._input_names)} inputs, got {len(args)}. "
                f"Input names: {self._input_names}"
            )

        # Determine output device from input tensors
        output_device = 'cpu'
        for tensor in args:
            if isinstance(tensor, torch.Tensor) and tensor.is_cuda:
                output_device = tensor.device
                break

        # Build input dict: convert torch tensors to numpy
        input_dict = {}
        for name, tensor in zip(self._input_names, args):
            if isinstance(tensor, torch.Tensor):
                input_dict[name] = tensor.detach().cpu().numpy()
            else:
                input_dict[name] = tensor

        # Run inference
        outputs = self._session.run(None, input_dict)

        # Convert outputs back to torch tensors on the appropriate device
        return [torch.from_numpy(out).to(output_device) for out in outputs]

class ExportBackend(abc.ABC):
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        # Only wrap if this class defines its own __init__
        if 'compile' in cls.__dict__:
            original_compile = cls.compile

            @functools.wraps(original_compile)
            def wrapped_compile(self, *args, **kwargs):
                model = original_compile(self, *args, **kwargs)
                if type(self) is cls:
                    pass
                    # TODO: run post-compilation validation if configured to do so
                    
                return model
            cls.compile = wrapped_compile
        
    def __init__(self, node_context, backend_params=None):
        self.node_context = node_context
        if backend_params is None:
            self.backend_params = {}
        else:
            self.backend_params = backend_params
        
        self.module_builder = ModuleBuilder(node_context)
    
    def override_module_builder(self, module_builder: Callable):
        self.module_builder = module_builder

    def _verify_model_location_and_get_hash(self, model_path):
        if not os.path.exists(model_path):
            _get_logger().error(f"Model file not found at {model_path}")
            return None, None
        with open(model_path, 'rb') as f:
            file_data = f.read()
            md5sum = hashlib.md5(file_data).hexdigest()
            sha256sum = hashlib.sha256(file_data).hexdigest()
        return md5sum, sha256sum

    def _copy_model_to_path(self, model_path, save_path):
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        if not os.path.exists(model_path):
            return None

        # Check if save_path is the same as the directory containing model_path
        model_dir = os.path.dirname(os.path.abspath(model_path))
        save_dir = os.path.abspath(save_path)
        if model_dir == save_dir:
            # No need to copy if already in the same directory
            return model_path

        # Get the filename from model_path
        filename = os.path.basename(model_path)
        # Create the full destination path
        dest_path = os.path.join(save_path, filename)
        # Copy the file
        shutil.copy2(model_path, dest_path)

        return dest_path

    @abc.abstractmethod
    def get_backed_model_type(self):
        raise NotImplementedError

    @abc.abstractmethod
    def compile(self) -> Any:
        '''
        Compiles the model.

        This function should return the compiled model. The resulting compiled model 
        can be used in recombination with other models.
        '''
        raise NotImplementedError

    @abc.abstractmethod
    def save(self, save_path: str, compiled_model: Any) -> Tuple[str, str, str]:
        '''
        Save the compiled model to the given path

        This function should apply all necessary optimizations
        '''
        raise NotImplementedError


class NoneExportBackend(ExportBackend):
    def __call__(self) -> Any:
        return self.compile()

    def compile(self) -> Any:
        if "model_path" not in self.backend_params:
            _get_logger().warning(
                f"No model path provided for {self.node_context.name}")
            _get_logger().warning("if this is intentional, please provide a path to the correct model "
                                "in the generated yaml file. Otherwise, please manually fill in the backend parameters.")
            return None

        # try to load the model if possible
        loaded_model = self.load_model()

        return loaded_model

    def save(self, save_path: str, compiled_model=None) -> Tuple[str, str, str]:
        if "model_path" not in self.backend_params or self.backend_params['model_path'] is None:
            return None, None, None
        md5sum, sha256sum = self._verify_model_location_and_get_hash(
            self.backend_params['model_path'])
        model_path = self.backend_params['model_path']

        if "copy_original_model" in self.backend_params and self.backend_params['copy_original_model'] is True:
            model_path = self._copy_model_to_path(model_path, save_path)

        return model_path, md5sum, sha256sum

    def load_model(self):
        backend_type = self.get_backed_model_type()
        if backend_type == "torch":
            return torch.jit.load(self.backend_params['model_path'])
        elif backend_type == "onnx":
            return SimplifiedONNXProgram(onnx.load(self.backend_params['model_path']))
        else:
            _get_logger().warning(
                f"LEAPP detected a {backend_type} model, but no load method is implemented for this backend")
            return None

    def get_backed_model_type(self):
        if "model_path" not in self.backend_params:
            return None

        path = self.backend_params['model_path']
        suffix = path.split('.')[-1]
        if suffix == 'pt':
            return "torch"
        elif suffix == 'pt2':
            return "torchscript2"
        elif suffix == 'onnx':
            return "onnx"
        elif suffix == 'cpp' or suffix == "cc":
            return "cpp"
        elif suffix == 'py':
            return "py"
        elif suffix == 'engine' or suffix == 'plan':
            return 'trt'
        else:
            raise Exception(
                f"Unsupported model file suffix: {suffix}")
