#
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import abc
from typing import Tuple, Any
import os
import hashlib
import shutil
from typing import Callable
import torch

from leapp._logging import _get_logger
from leapp.backends.module_builder import ModuleBuilder



import onnx
import onnxruntime as ort


class SimplifiedONNXProgram:
    """Wrapper for ONNX models.

    This class mimics the behavior of ONNXProgram generated by torch.onnx.export
    with onnx-dynamo, allowing the model to be called directly for inference.

    Keeps source files on disk and copies on save. Cleans up temp dir on delete.
    """

    def __init__(self, onnx_model_path, device=None, temp_dir=None):
        """Initialize the ONNX program.

        Args:
            onnx_model_path: Path to an ONNX file.
            device: Device to run on ('cuda', 'cpu', or None for auto-detect).
                    If None, will use CUDA if available, otherwise CPU.
            temp_dir: If provided, this temp directory will be cleaned up when the object is deleted.
        """
        self._device = device
        model_path = str(onnx_model_path)
        self._source_dir = os.path.dirname(os.path.abspath(model_path))
        self._source_filename = os.path.basename(model_path)
        self._temp_dir = temp_dir

        # Session created lazily on first __call__
        self._session = None
        self._input_names = None
        self._active_provider = None

    def __del__(self):
        """Clean up temp directory if we own it."""
        if getattr(self, '_temp_dir', None) is not None:
            import shutil
            try:
                if os.path.exists(self._temp_dir):
                    shutil.rmtree(self._temp_dir)
            except Exception:
                pass  # Silently ignore cleanup errors

    def _get_providers(self, device):
        """Get the list of execution providers based on device preference."""
        available_providers = ort.get_available_providers()

        if device is None:
            # Auto-detect: prefer CUDA if available
            if 'CUDAExecutionProvider' in available_providers:
                return ['CUDAExecutionProvider', 'CPUExecutionProvider']
            return ['CPUExecutionProvider']
        elif device == 'cuda' or (isinstance(device, torch.device) and device.type == 'cuda'):
            if 'CUDAExecutionProvider' not in available_providers:
                _get_logger().warning(
                    "CUDA execution provider requested but not available. Falling back to CPU."
                )
                return ['CPUExecutionProvider']
            return ['CUDAExecutionProvider', 'CPUExecutionProvider']
        else:
            return ['CPUExecutionProvider']

    def _get_source_size(self):
        """Get total size of all files in the source directory."""
        total_size = 0
        files_info = []
        for f in os.listdir(self._source_dir):
            file_path = os.path.join(self._source_dir, f)
            if os.path.isfile(file_path):
                size = os.path.getsize(file_path)
                total_size += size
                files_info.append(f"{f} ({size / (1024**2):.2f} MB)")

        return total_size

    def save(self, destination, include_initializers=True, keep_initializers_as_inputs=False):
        """Save the ONNX model to disk.

        For large models (>2GB), re-saves with external data format.
        For small models, copies files directly.
        """
        import shutil

        # 2GB threshold for protobuf limit
        SIZE_THRESHOLD = 2 * 1024 * 1024 * 1024

        dest_dir = os.path.dirname(os.path.abspath(destination))
        dest_filename = os.path.basename(destination)
        src_path = os.path.join(self._source_dir, self._source_filename)

        total_size = self._get_source_size()

        if total_size > SIZE_THRESHOLD:
            # Large model - load and re-save with external data
            _get_logger().info(
                f"Large model (~{total_size / (1024**3):.2f} GB) - saving with external data format"
            )
            # Ensure destination directory exists
            os.makedirs(dest_dir, exist_ok=True)

            model_proto = onnx.load(src_path, load_external_data=True)
            data_filename = dest_filename + ".data"
            data_path = os.path.join(dest_dir, data_filename)

            # Delete existing data file to avoid appending (ONNX appends instead of overwriting)
            if os.path.exists(data_path):
                os.remove(data_path)

            _get_logger().info(
                f"Saving model to {destination} with external data in {data_filename}")
            onnx.save(
                model_proto,
                destination,
                save_as_external_data=True,
                all_tensors_to_one_file=True,
                location=data_filename,
                size_threshold=1024,
                convert_attribute=True,  # Also convert Constant node attributes
            )

            # Verify external data file was created
            expected_data_path = os.path.join(dest_dir, data_filename)
            if os.path.exists(expected_data_path):
                _get_logger().info(
                    f"External data file created: {expected_data_path}")
            else:
                _get_logger().warning(
                    f"External data file NOT found: {expected_data_path}")
        else:
            # Small model - just copy files
            shutil.copy2(src_path, destination)

            # Copy ALL other files from source directory (external data files)
            for f in os.listdir(self._source_dir):
                if f != self._source_filename:
                    src_file = os.path.join(self._source_dir, f)
                    if os.path.isfile(src_file):
                        dst_file = os.path.join(dest_dir, f)
                        shutil.copy2(src_file, dst_file)

    def _ensure_session(self):
        """Create the inference session if not already created."""
        if self._session is None:
            model_path = os.path.join(self._source_dir, self._source_filename)
            providers = self._get_providers(self._device)
            sess_options = ort.SessionOptions()
            # ORT_ENABLE_ALL can silently corrupt results for certain graph
            # patterns (e.g. Gemm chains produced by FX make_fx decomposition).
            # ORT_ENABLE_BASIC is safe and still applies constant folding.
            sess_options.graph_optimization_level = (
                ort.GraphOptimizationLevel.ORT_ENABLE_BASIC)
            self._session = ort.InferenceSession(
                model_path, sess_options, providers=providers)
            self._input_names = [
                inp.name for inp in self._session.get_inputs()]
            self._active_provider = self._session.get_providers(
            )[0] if self._session.get_providers() else 'CPUExecutionProvider'

    def __call__(self, *args):
        """Run inference on the ONNX model.

        Args:
            *args: Input tensors in order, matching the model's input signature.

        Returns:
            List of output tensors as torch.Tensor objects on the same device as inputs.
        """
        self._ensure_session()

        if len(args) != len(self._input_names):
            raise ValueError(
                f"Expected {len(self._input_names)} inputs, got {len(args)}. "
                f"Input names: {self._input_names}"
            )

        # Determine output device from input tensors
        output_device = 'cpu'
        for tensor in args:
            if isinstance(tensor, torch.Tensor) and tensor.is_cuda:
                output_device = tensor.device
                break

        # Build input dict: convert torch tensors to numpy
        input_dict = {}
        for name, tensor in zip(self._input_names, args):
            if isinstance(tensor, torch.Tensor):
                input_dict[name] = tensor.detach().cpu().numpy()
            else:
                input_dict[name] = tensor

        # Run inference
        outputs = self._session.run(None, input_dict)

        # Convert outputs back to torch tensors on the appropriate device
        return tuple(torch.from_numpy(out).to(output_device) for out in outputs)


def prepare_tensors_for_export(tensors):
    """
    Prepare tensors for export by cloning them to escape inference mode.

    Tensors created under torch.inference_mode() cannot participate in autograd,
    which causes torch.export.export() (used by dynamo) to fail with:
    "RuntimeError: Inference tensors cannot be saved for backward."

    Cloning creates new tensors that are not marked as inference tensors.

    Args:
        tensors: A sequence of tensors (or other values) to prepare.

    Returns:
        A tuple of prepared tensors (cloned if they were torch.Tensor).
    """
    prepared = []
    for t in tensors:
        if isinstance(t, torch.Tensor):
            if hasattr(t, 'original_clone'):
                prepared.append(t.original_clone())
            else:
                prepared.append(t.clone())
        else:
            prepared.append(t)
    return tuple(prepared)


class ExportBackend(abc.ABC):
    def __init__(self, node_context, backend_params=None):
        self.node_context = node_context
        if backend_params is None:
            self.backend_params = {}
        else:
            self.backend_params = backend_params

        self.module_builder = ModuleBuilder(node_context)

        self.compiled_model = None
        self.compiled_module = None
    
    def override_module_builder(self, module_builder: Callable):
        self.module_builder = module_builder

    def _verify_model_location_and_get_hash(self, model_path):
        if not os.path.exists(model_path):
            _get_logger().error(f"Model file not found at {model_path}")
            return None, None
        with open(model_path, 'rb') as f:
            file_data = f.read()
            md5sum = hashlib.md5(file_data).hexdigest()
            sha256sum = hashlib.sha256(file_data).hexdigest()
        return md5sum, sha256sum

    def _copy_model_to_path(self, model_path, save_path):
        if not os.path.exists(save_path):
            os.makedirs(save_path)
        if not os.path.exists(model_path):
            return None

        # Check if save_path is the same as the directory containing model_path
        model_dir = os.path.dirname(os.path.abspath(model_path))
        save_dir = os.path.abspath(save_path)
        if model_dir == save_dir:
            # No need to copy if already in the same directory
            return model_path

        # Get the filename from model_path
        filename = os.path.basename(model_path)
        # Create the full destination path
        dest_path = os.path.join(save_path, filename)
        # Copy the file
        shutil.copy2(model_path, dest_path)

        return dest_path

    @abc.abstractmethod
    def get_backed_model_type(self):
        raise NotImplementedError

    @abc.abstractmethod
    def get_backend_metadata(self) -> dict:
        """Optional backend-specific metadata to include in node YAML parameters."""
        return {}

    @abc.abstractmethod
    def compile(self, m: torch.nn.Module = None) -> Any:
        '''
        Compiles the model.

        This function should return the compiled model. The resulting compiled model 
        can be used in recombination with other models.
        '''
        raise NotImplementedError

    @abc.abstractmethod
    def save(self, save_path: str) -> Tuple[str, str, str]:
        '''
        Save the compiled model to the given path

        This function should apply all necessary optimizations
        '''
        raise NotImplementedError

    @abc.abstractmethod
    def load(self, model_path: str, sha256sum: str, device: str):
        raise NotImplementedError
    
    def _load_onnx(self, model_path: str, sha256sum: str, device: str):
        _, actual_sha256sum = self._verify_model_location_and_get_hash(
            model_path)
        if actual_sha256sum != sha256sum:
            raise ValueError(
                f"SHA256 checksum mismatch for {model_path}: "
                f"expected {sha256sum}, got {actual_sha256sum}"
            )
        model = SimplifiedONNXProgram(model_path, device=device)
        self.compiled_model = model
        self.compiled_module = None # ONNX models cannot be represented as a module for reexport.
    
    def _load_torchscript(self, model_path: str, sha256sum: str, device: str):
        _, actual_sha256sum = self._verify_model_location_and_get_hash(
            model_path)
        if actual_sha256sum != sha256sum:
            raise ValueError(
                f"SHA256 checksum mismatch for {model_path}: "
                f"expected {sha256sum}, got {actual_sha256sum}"
            )
        model = torch.jit.load(model_path)
        self.compiled_model = model.eval()
        self.compiled_module = model


class NoneExportBackend(ExportBackend):
    def get_backend_metadata(self):
        return {}

    def compile(self, m: torch.nn.Module = None):
        if "model_path" not in self.backend_params or self.backend_params['model_path'] is None:
            _get_logger().warning(
                f"No model path provided for {self.node_context.name}")
            _get_logger().warning("if this is intentional, please provide a path to the correct model "
                                  "in the generated yaml file. Otherwise, please manually fill in the backend parameters.")
        else:
            _, sha256sum = self._verify_model_location_and_get_hash(self.backend_params['model_path'])
            device = 'cuda' if torch.cuda.is_available() else 'cpu'
            device = self.backend_params['device'] if 'device' in self.backend_params else device
            self.load(self.backend_params['model_path'], sha256sum, device, self.get_backed_model_type())


    def save(self, save_path: str) -> Tuple[str, str, str]:
        if "model_path" not in self.backend_params or self.backend_params['model_path'] is None:
            return None, None, None
        md5sum, sha256sum = self._verify_model_location_and_get_hash(
            self.backend_params['model_path'])
        model_path = self.backend_params['model_path']

        if "copy_original_model" in self.backend_params and self.backend_params['copy_original_model'] is True:
            model_path = self._copy_model_to_path(model_path, save_path)

        return model_path, md5sum, sha256sum

    def load(self, model_path: str, sha256sum: str, device: str, type=None):
        if type is None: 
            return
        if type == "onnx":
            self._load_onnx(model_path, sha256sum, device)
        elif type == "jit":
            self._load_torchscript(model_path, sha256sum, device)
        else:
            raise Exception(f"Unsupported model type: {type}")

    def get_backed_model_type(self):
        if "model_path" not in self.backend_params:
            return None

        path = self.backend_params['model_path']
        suffix = path.split('.')[-1]
        if suffix == 'pt':
            return "jit"
        elif suffix == 'pt2':
            return "torchscript2"
        elif suffix == 'onnx':
            return "onnx"
        elif suffix == 'cpp' or suffix == "cc":
            return "cpp"
        elif suffix == 'py':
            return "py"
        elif suffix == 'engine' or suffix == 'plan':
            return 'trt'
        else:
            raise Exception(
                f"Unsupported model file suffix: {suffix}")
