import torch
from typing import Tuple
from leapp.backends.export_backend import ExportBackend, prepare_tensors_for_export
from leapp._logging import _get_logger
import os
import onnx
import tempfile

import onnxruntime as ort


class SimplifiedONNXProgram:
    """Wrapper for ONNX models.

    This class mimics the behavior of ONNXProgram generated by torch.onnx.export
    with dynamo=True, allowing the model to be called directly for inference.

    Keeps source files on disk and copies on save. Cleans up temp dir on delete.
    """

    def __init__(self, onnx_model_path, device=None, temp_dir=None):
        """Initialize the ONNX program.

        Args:
            onnx_model_path: Path to an ONNX file.
            device: Device to run on ('cuda', 'cpu', or None for auto-detect).
                    If None, will use CUDA if available, otherwise CPU.
            temp_dir: If provided, this temp directory will be cleaned up when the object is deleted.
        """
        self._device = device
        model_path = str(onnx_model_path)
        self._source_dir = os.path.dirname(os.path.abspath(model_path))
        self._source_filename = os.path.basename(model_path)
        self._temp_dir = temp_dir

        # Session created lazily on first __call__
        self._session = None
        self._input_names = None
        self._active_provider = None

    def __del__(self):
        """Clean up temp directory if we own it."""
        if getattr(self, '_temp_dir', None) is not None:
            import shutil
            try:
                if os.path.exists(self._temp_dir):
                    shutil.rmtree(self._temp_dir)
            except Exception:
                pass  # Silently ignore cleanup errors

    def _get_providers(self, device):
        """Get the list of execution providers based on device preference."""
        available_providers = ort.get_available_providers()

        if device is None:
            # Auto-detect: prefer CUDA if available
            if 'CUDAExecutionProvider' in available_providers:
                return ['CUDAExecutionProvider', 'CPUExecutionProvider']
            return ['CPUExecutionProvider']
        elif device == 'cuda' or (isinstance(device, torch.device) and device.type == 'cuda'):
            if 'CUDAExecutionProvider' not in available_providers:
                _get_logger().warning(
                    "CUDA execution provider requested but not available. Falling back to CPU."
                )
                return ['CPUExecutionProvider']
            return ['CUDAExecutionProvider', 'CPUExecutionProvider']
        else:
            return ['CPUExecutionProvider']

    def _get_source_size(self):
        """Get total size of all files in the source directory."""
        total_size = 0
        files_info = []
        for f in os.listdir(self._source_dir):
            file_path = os.path.join(self._source_dir, f)
            if os.path.isfile(file_path):
                size = os.path.getsize(file_path)
                total_size += size
                files_info.append(f"{f} ({size / (1024**2):.2f} MB)")

        # _get_logger().debug(
        #     f"Source directory contents: {', '.join(files_info)}. "
        #     f"Total size: {total_size / (1024**3):.2f} GB"
        # )
        return total_size

    def save(self, destination, include_initializers=True, keep_initializers_as_inputs=False):
        """Save the ONNX model to disk.

        For large models (>2GB), re-saves with external data format.
        For small models, copies files directly.
        """
        import shutil

        # 2GB threshold for protobuf limit
        SIZE_THRESHOLD = 2 * 1024 * 1024 * 1024

        dest_dir = os.path.dirname(os.path.abspath(destination))
        dest_filename = os.path.basename(destination)
        src_path = os.path.join(self._source_dir, self._source_filename)

        total_size = self._get_source_size()

        if total_size > SIZE_THRESHOLD:
            # Large model - load and re-save with external data
            _get_logger().info(
                f"Large model (~{total_size / (1024**3):.2f} GB) - saving with external data format"
            )
            # Ensure destination directory exists
            os.makedirs(dest_dir, exist_ok=True)

            model_proto = onnx.load(src_path, load_external_data=True)
            data_filename = dest_filename + ".data"
            data_path = os.path.join(dest_dir, data_filename)

            # Delete existing data file to avoid appending (ONNX appends instead of overwriting)
            if os.path.exists(data_path):
                os.remove(data_path)

            _get_logger().info(
                f"Saving model to {destination} with external data in {data_filename}")
            onnx.save(
                model_proto,
                destination,
                save_as_external_data=True,
                all_tensors_to_one_file=True,
                location=data_filename,
                size_threshold=1024,
                convert_attribute=True,  # Also convert Constant node attributes
            )

            # Verify external data file was created
            expected_data_path = os.path.join(dest_dir, data_filename)
            if os.path.exists(expected_data_path):
                _get_logger().info(
                    f"External data file created: {expected_data_path}")
            else:
                _get_logger().warning(
                    f"External data file NOT found: {expected_data_path}")
        else:
            # Small model - just copy files
            shutil.copy2(src_path, destination)

            # Copy ALL other files from source directory (external data files)
            for f in os.listdir(self._source_dir):
                if f != self._source_filename:
                    src_file = os.path.join(self._source_dir, f)
                    if os.path.isfile(src_file):
                        dst_file = os.path.join(dest_dir, f)
                        shutil.copy2(src_file, dst_file)

    def _ensure_session(self):
        """Create the inference session if not already created."""
        if self._session is None:
            model_path = os.path.join(self._source_dir, self._source_filename)
            providers = self._get_providers(self._device)
            self._session = ort.InferenceSession(
                model_path, providers=providers)
            self._input_names = [
                inp.name for inp in self._session.get_inputs()]
            self._active_provider = self._session.get_providers(
            )[0] if self._session.get_providers() else 'CPUExecutionProvider'

    def __call__(self, *args):
        """Run inference on the ONNX model.

        Args:
            *args: Input tensors in order, matching the model's input signature.

        Returns:
            List of output tensors as torch.Tensor objects on the same device as inputs.
        """
        self._ensure_session()

        if len(args) != len(self._input_names):
            raise ValueError(
                f"Expected {len(self._input_names)} inputs, got {len(args)}. "
                f"Input names: {self._input_names}"
            )

        # Determine output device from input tensors
        output_device = 'cpu'
        for tensor in args:
            if isinstance(tensor, torch.Tensor) and tensor.is_cuda:
                output_device = tensor.device
                break

        # Build input dict: convert torch tensors to numpy
        input_dict = {}
        for name, tensor in zip(self._input_names, args):
            if isinstance(tensor, torch.Tensor):
                input_dict[name] = tensor.detach().cpu().numpy()
            else:
                input_dict[name] = tensor

        # Run inference
        outputs = self._session.run(None, input_dict)

        # Convert outputs back to torch tensors on the appropriate device
        return tuple(torch.from_numpy(out).to(output_device) for out in outputs)


class ONNXExportBackend(ExportBackend):
    def get_backed_model_type(self):
        return "onnx"

    def load(self, model_path: str, sha256sum: str, device: str):
        _, actual_sha256sum = self._verify_model_location_and_get_hash(
            model_path)
        if actual_sha256sum != sha256sum:
            raise ValueError(
                f"SHA256 checksum mismatch for {model_path}: "
                f"expected {sha256sum}, got {actual_sha256sum}"
            )
        model = SimplifiedONNXProgram(model_path, device=device)
        return model

    def compile_dynamo(self, m):
        # Get flat tensor values directly from inputs (not input_formats which preserves nested structure)
        input_values = tuple(
            [tensor_desc.value for tensor_desc in self.node_context.inputs])
        # Clone tensors to escape inference mode (inference tensors can't participate in autograd)
        input_values = prepare_tensors_for_export(input_values)
        onnx_program = torch.onnx.export(
            m,
            input_values,
            None,  # no need to save the model
            dynamo=True,
            input_names=[
                tensor_desc.name for tensor_desc in self.node_context.inputs],
            output_names=[
                tensor_desc.name for tensor_desc in self.node_context.outputs],

            verify=self.backend_params.get('verify', True),
            optimize=self.backend_params.get('optimize', True),

            verbose=_get_logger().is_verbose(),
            report=self.backend_params.get('report', False),
            fallback=self.backend_params.get('fallback', None),
            opset_version=self.backend_params.get('opset_version', None),
        )

        return onnx_program

    def compile_torchscript(self, m):
        # Get flat tensor values directly from inputs (not input_formats which preserves nested structure)
        input_values = tuple(
            [tensor_desc.value for tensor_desc in self.node_context.inputs])
        # Clone tensors to escape inference mode (inference tensors can't participate in autograd)
        input_values = prepare_tensors_for_export(input_values)

        # Create temp directory manually (not context manager) so we can control its lifetime
        tmpdir = tempfile.mkdtemp()
        save_path = os.path.join(tmpdir, "model.onnx")

        torch.onnx.export(
            m,
            input_values,
            save_path,
            dynamo=False,
            input_names=[
                tensor_desc.name for tensor_desc in self.node_context.inputs],
            output_names=[
                tensor_desc.name for tensor_desc in self.node_context.outputs],

            verbose=_get_logger().is_verbose(),
            report=self.backend_params.get('report', False),
            opset_version=self.backend_params.get('opset_version', None),
        )

        # Create program from file path
        # Temp dir will be cleaned up when program is deleted
        onnx_program = SimplifiedONNXProgram(save_path, temp_dir=tmpdir)

        return onnx_program

    def compile(self):
        m = self.module_builder().eval()
        # TODO: make this conditional upon use_trace
        if self.backend_params.get('prescript', False):
            m = torch.jit.script(m)

        if self.backend_params.get('dynamo', True):
            onnx_model = self.compile_dynamo(m)
        else:
            onnx_model = self.compile_torchscript(m)
            
        # Sync inputs with what ONNX actually exported
        # (ONNX can remove unused inputs during optimization)
        self._sync_inputs_with_onnx(onnx_model)
        return onnx_model

    def save(self, save_path: str, compiled_model) -> Tuple[str, str, str]:
        onnx_path = os.path.join(save_path, f"{self.node_context.name}.onnx")

        # Use ONNXProgram's save method
        compiled_model.save(
            onnx_path,
            include_initializers=True,
            keep_initializers_as_inputs=False,
        )

        # Validate model (skip for large models as it can fail with protobuf limits)
        skip_validation = self.backend_params.get('skip_validation', False)
        if not skip_validation:
            try:
                # Try to check model, but don't fail the export if validation fails
                onnx.checker.check_model(onnx_path)
            except Exception as e:
                _get_logger().error(
                    f"ONNX model validation warning (model still saved): {e}")

        md5sum, sha256sum = self._verify_model_location_and_get_hash(onnx_path)

        return onnx_path, md5sum, sha256sum

    def _get_onnx_model(self, onnx_program):
        """Get the ONNX model proto from an ONNX program."""
        if hasattr(onnx_program, 'model_proto'):
            # dynamo export returns ONNXProgram with model_proto
            return onnx_program.model_proto
        else:
            # SimplifiedONNXProgram - load from file
            model_path = os.path.join(onnx_program._source_dir, onnx_program._source_filename)
            return onnx.load(model_path)

    def _get_actual_onnx_inputs(self, onnx_model):
        """Get actual input names from ONNX model, excluding initializers (constants)."""
        # Initializers are constants baked into the model - exclude them
        initializer_names = {init.name for init in onnx_model.graph.initializer}
        
        # Return only true dynamic inputs
        return [inp.name for inp in onnx_model.graph.input if inp.name not in initializer_names]

    def _sync_inputs_with_onnx(self, onnx_program):
        """Sync inputs with what ONNX actually exported.
        
        ONNX export can remove unused inputs (constant folding, dead code elimination).
        This is allowed and we update node_context.inputs accordingly.
        
        However, if ONNX renames inputs (which happens with identity/passthrough functions
        when using dynamo=True), we raise an error and suggest using dynamo=False.
        """
        onnx_model = self._get_onnx_model(onnx_program)
        
        expected_input_names = set(td.name for td in self.node_context.inputs)
        actual_input_names = self._get_actual_onnx_inputs(onnx_model)
        actual_input_set = set(actual_input_names)
        
        # Check for removed inputs (this is OK - ONNX optimized them away)
        removed_inputs = [td.name for td in self.node_context.inputs if td.name not in actual_input_set]
        
        # Check for renamed/new inputs (this is NOT OK - we can't track them)
        renamed_inputs = [name for name in actual_input_names if name not in expected_input_names]
        
        if renamed_inputs:
            raise ValueError(
                f"[{self.node_context.name}] ONNX export renamed inputs: {renamed_inputs}. "
                f"This typically happens with identity/passthrough functions when using dynamo=True. "
                f"This usecase is not supported by LEAPP, please: \n"
                f"1. use dynamo=False by setting backend_params={{'dynamo': False}} \n"
                f"2. use a different backend, such as torch-script or torch-trace \n"
                f"3. remove the inputs that are not used in the computation or directly returned as output"
            )
        
        if removed_inputs:
            _get_logger().warning(
                f"[{self.node_context.name}] ONNX export optimized away {len(removed_inputs)} inputs: {removed_inputs}. "
                f"These inputs were unused or became constants. Updating node to match."
            )
            # Track trimmed inputs
            self.node_context.trimmed_inputs.update(removed_inputs)
            
            # Filter inputs to only keep actual ONNX inputs (preserving order)
            self.node_context.inputs = [
                td for td in self.node_context.inputs if td.name in actual_input_set
            ]
